title: "Ramakant // Notes"
description: A personal blog powered by Jekyll
author: ramakantyadav.in
email: ramakant.yadav@gmail.com
phone: "8618086165"
url: https://iramakant.github.io
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock